### ISSUE TITLE
Sbt

### ISSUE THREAD

**Issue by harscoet** [Stratio/spark-mongodb#1]
Is it possible to use this library with sbt dependency management ?

**Comment by JSantosP** [comment]
We only support Maven, but it's possible to handle sbt dependency management by using:

https://github.com/shivawu/sbt-maven-plugin

or any other similar plugin

**Comment by koertkuipers** [comment]
i was able to build it with sbt no problem. didnt bother to integrate with maven. i needed it since i wanted to crossbuild for scala 2.11 and publish artifacts with scala version.

**Comment by linbojin** [comment]
libraryDependencies += "com.stratio.datasource" % "spark-mongodb_2.10" % "0.10.0"
