### ISSUE TITLE
incremental data

### ISSUE THREAD

**Issue by michaelbacci** [Stratio/spark-mongodb#10]
Hi, do you know a way to load INCREMENTAL data from MongoDb ?
Here the problem:
I have a document in mongoDb that grow every minute and I need to get new data
within spark to deal with the fresh data.
So, I'm looking for something like this:

Step 1: set connector for mongodb + option to reload data every 60 seconds (or in real time ?)
Step 2: signal (80 [sec] (or when refresh is done), run my_new_stat())
Where my_new_stat() is a function where I use spark with the refresh data merged/added with the oldest.

any idea ?
Thanks

**Comment by dmorales-stratio** [comment]
Just take a look at Stratio Sparkta, a real time aggregation engine based
on spark streaming (we can write rollups to mongoDB).

http://docs.stratio.com/modules/sparkta/development/

https://github.com/Stratio/sparkta





2015-07-29 15:15 GMT+02:00 Michael <notifications@github.com>:

> Hi, do you know a way to load INCREMENTAL data from MongoDb ?
> Here the problem:
> I have a document in mongoDb that grow every minute and I need to get new
> data
> within spark to deal with the fresh data.
> So, I'm looking for something like this:
>
> Step 1: set connector for mongodb + option to reload data every 60 seconds
> (or in real time ?)
> Step 2: signal (80 sec <http://or%20when%20refresh%20is%20done>, run
> my_new_stat())
> Where my_new_stat() is a function where I use spark with the refresh data
> merged/added with the oldest.
>
> any idea ?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/spark-mongodb/issues/10>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*
