### ISSUE TITLE
Please Guide how to store a dataframe to MongDB from Python( Pyspark)

### ISSUE THREAD

**Issue by raghavchalapathy** [Stratio/Spark-MongoDB#105]
Hello 

Many thanks for the spark-MongoDB module

Currently i am able to do 

sqlCtx.sql("CREATE TEMPORARY TABLE  mongoTable(Timestamp STRING, Volume INTEGER) USING com.stratio.datasource.mongodb OPTIONS (host '127.0.0.1:27017', database 'marketdata', collection 'minbars')")
df = sqlCtx.sql("SELECT * FROM mongoTable ")
df.show()

Could you please guide me How to save a dataframe(returned from Spark sqlContext) from python to MongoDB

with regards
Raghav

**Comment by cperezmig** [comment]
Not sure if correct but I personally make this:

`df.write.format("com.stratio.datasource.mongodb").mode('append').options(host=mongodb, database=dbname, collection=colname, idField='_id', splitKey='_id').save()`

Best regards

**Comment by raghavchalapathy** [comment]
Thanks a lot it works for me as well
