### ISSUE TITLE
Connection not getting closed 

### ISSUE THREAD

**Issue by Velmuruganms12** [Stratio/Spark-MongoDB#109]
I used spark-mongodb_2.10 version 0.10.0 for spark 1.5.0 & Mongo 3.2.  But today we tried  upgrading  spark to 1.6.1 latest version so we have changed spark-mongodb_2.10 to version 0.11.0.

But we see connection opened are not getting closed and MongodbConfigBuilder instance is not getting disconnected so application keeps running till we try to stop it manually.

Any one faced similar issue ? Let me know if any configuration changes need to be done.

<dependencies>
<dependency>
	<groupId>org.apache.spark</groupId>
	<artifactId>spark-core_2.10</artifactId>
	<version>1.6.1</version>
		<scope>compile</scope>
</dependency>

	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-sql_2.10</artifactId>
		<version>1.6.1</version>
			<scope>compile</scope>
	</dependency>
		<dependency>
			<groupId>com.stratio.datasource</groupId>
			<artifactId>spark-mongodb_2.10</artifactId>
			<version>0.11.0</version>
		</dependency>

	</dependencies>

    val mcInputBuilder = MongodbConfigBuilder(Map(MongodbConfig.Host -> List(MongoHost + ":" + MongoPort), MongodbConfig.Database -> databaseName, MongodbConfig.Collection -> tableName,
      MongodbConfig.SamplingRatio -> 1.0, MongodbConfig.WriteConcern -> MongodbWriteConcern.Normal, MongodbConfig.SplitSize -> 10000))
    val mongoRDD = sqlContext.fromMongoDB(mcInputBuilder.build())
    mongoRDD.registerTempTable(tableName)

**Comment by ashreyashi** [comment]
Hi,

I'm facing exactly the same problem. It keeps the mongo connection open and accumulates the open connection which is resulting in OOM error.

Asvin

**Comment by zhangwenzhao** [comment]
me too

**Comment by pmadrigal** [comment]
Hi all,

It is a known bug in wich we are working. You will be notified when it is solved.

Thanks a lot for your feedback!

**Comment by miguel0afd** [comment]
Hi everyone,

next week, we'll be dealing this issue.

**Comment by pfcoperez** [comment]
Thanks to @wuciawem 's contribution this issue has been fixed.
