### ISSUE TITLE
执行后不自动 结束  mongodb

### ISSUE THREAD

**Issue by zhangwenzhao** [Stratio/Spark-MongoDB#110]
mgDF = sqlContext.read.format("com.stratio.datasource.mongodb").options(
        credentials="xxxxxxxxx",
        collection="xxxxx",
        host="xxxxxxx",
        database="xxxxxxx").load()
    mgDF.registerTempTable("mgDF")

执行后  任务不结束 数据 已经打印完了 不自动 结束

**Comment by miguel0afd** [comment]
Hi @zhangwenzhao 

could you provide information about the issue in english, please?

**Comment by wuciawe** [comment]
@miguel0afd He means the same problem in #109

**Comment by miguel0afd** [comment]
Ok, thanks for the information. Next week, the issue #109 will be fixed.
