### ISSUE TITLE
Broken schema discovery for heterogeneous arrays

### ISSUE THREAD

**Issue by ssimeonov** [Stratio/Spark-MongoDB#113]
It seems that schema discovery for documents with heterogeneous arrays just picks the type of the first element or, perhaps, maps everything to string. For example, a field value such as `["props", {a: 1, b: 2}]` is mapped to `array<string>`.

**Comment by pfcoperez** [comment]
Hi @ssimeonov , Spark's type for arrays is [ArrayType](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.types.ArrayType). As you can see from the documentation, these arrays have an unique element type:

```scala
ArrayType(**elementType**: DataType, ....)
```

The connector iterates over each heterogeneous array element finding a compatible common type ancestor: For example, it can deduce `DoubleType` can represent both real and integer numbers.
If it finds two different structures such as `{a: 1, b: 2}` and `{c: "hello"}` it infers a common structure type: `{a: 1, b: 2, c: "hello"}`.  These "type merging policies are expressed by the [compatibleType](https://github.com/Stratio/Spark-MongoDB/blob/506be658d99513bfb423d548a316286fc858142f/spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/schema/MongodbSchema.scala#L80).

At the end of the day, the connector need to return a Spark compatible type, unfortunately, there is not a heterogeneous `ArrayType` in Spark yet. We could invest some time in implementing that type but, is that the right thing to do?

From [Learning Spark,](http://shop.oreilly.com/product/0636920028512.do) Chapter 9: 

> Structured data is any data that has a schema—that is, a known
> set of fields for each record

...
...
...

> Under the hood, Spark SQL is based on an extension of the RDD model called a
> DataFrame. A DataFrame contains an RDD of Row objects, each representing a
> record. A DataFrame also knows the schema (i.e., data fields) of its rows. DataFrames
> store data in a more efficient manner than native RDDs, taking advantage of their
> schema

From those paragraphs I understand that schema inference implies passing from semi structured to structured data. The latter being conceptually incompatible with heterogeneous arrays.

**Comment by ssimeonov** [comment]
In that case, `array<string>` does make sense, provided all values are valid JSON strings.

**Comment by pfcoperez** [comment]
@ssimeonov It does :smile:
