### ISSUE TITLE
saveToMongoDB doesnt accept deepconfig

### ISSUE THREAD

**Issue by mjaayson** [Stratio/Spark-MongoDB#120]
def saveToMongodb(config : com.stratio.datasource.util.Config, batch : scala.Boolean = { /* compiled code */ }) : scala.Unit = { /* compiled code */ }

What it accepts is a Config and not a deepConfig. Is there an override some where ?

**Comment by pfcoperez** [comment]
`DeepConfig` has been named just `Config` since commit https://github.com/Stratio/Spark-MongoDB/commit/3b8cc0d923881f4bc9ede3dee36fd532d156efdf
