### ISSUE TITLE
Query times out on long running applications

### ISSUE THREAD

**Issue by sfines** [Stratio/spark-mongodb#20]
My network is sometimes less reliable than I would wish, which leads to the following exception: 

2015-08-27 12:20:48.381|Executor task launch worker-0|ERROR|org.apache.spark.executor.Executor|||||||Exception in task 0.0 in stage 1.0 (TID 1)
com.mongodb.MongoTimeoutException: Timed out after 10000 ms while waiting for a server that matches com.mongodb.ServerAddressSelector@28a60f2f. Client view of cluster state is {type=ReplicaSet, servers=[{address=drtqn1pdmongo01.infosolco.net:27017, type=ReplicaSetPrimary, averageLatency=41.5 ms, state=Connected}, {address=drtqn1pdmongo02.infosolco.net:27017, type=ReplicaSetSecondary, averageLatency=41.2 ms, state=Connected}, {address=drtqn1pdmongo03.infosolco.net:27017, type=ReplicaSetSecondary, averageLatency=41.3 ms, state=Connected}]
	at com.mongodb.BaseCluster.getServer(BaseCluster.java:82) ~[mongo-java-driver-2.13.1.jar:na]
	at com.mongodb.DBTCPConnector.getServer(DBTCPConnector.java:656) ~[mongo-java-driver-2.13.1.jar:na]

I would like to be able to set the driver timeout from the MongodbConfig to manage this issue.

**Comment by JSantosP** [comment]
@pmadrigal I guess that, as it's as easy as writting a couple of lines in [MongodbConfig.scala](https://github.com/Stratio/spark-mongodb/blob/master/spark-mongodb/src/main/scala/com/stratio/provider/mongodb/mongodbConfig.scala) and [MongodbClientFactory.scala](https://github.com/Stratio/spark-mongodb/blob/master/spark-mongodb/src/main/scala/com/stratio/provider/mongodb/MongodbClientFactory.scala), I would include the possibility of reading all missing properties included [here](http://stackoverflow.com/a/6521704) (Read preference and write concern are already included) :-)

**Comment by pmadrigal** [comment]
We will develop this as soon as possible.

Thanks for your feedback! :)

**Comment by pmadrigal** [comment]
Timeout option is already available!!
