### ISSUE TITLE
Relation Equality

### ISSUE THREAD

**Issue by kanielc** [Stratio/spark-mongodb#24]
Spark does some optimizations based on whether two relations are the same.  In the Spark-Avro reference implementation, we can see the ``` equals ``` method implemented.
https://github.com/databricks/spark-avro/blob/01ae707bf3dbe3e74cfc8b04e892eb34defd28fe/src/main/scala/com/databricks/spark/avro/AvroRelation.scala#L189

I'm thinking this should be implemented as well for ```MongodbRelation``` to reduce the number of trips to Mongo.  I can implement this, what I'm wondering is: under what conditions do we consider two Mongo Relations the same?  Do we want to go to Mongo each time if 2 dataframes are created with the same specs?

My instinct for equality would be same config and same schema.

**Comment by pmadrigal** [comment]
We are going to implement it!

Thank you very much!
