### ISSUE TITLE
artifact name should include scala binary version postfix

### ISSUE THREAD

**Issue by koertkuipers** [Stratio/spark-mongodb#28]
i tried to use the new maven build with -Pscala-2.11 and it works well. nice! 

however the produced artifact does not include the scala version postfix. artifacts should be spark-mongodb-core_2.10 and spark-mongodb-core_2.11, so that people can use it safely with different scala versions.

**Comment by koertkuipers** [comment]
well i tried to use maven to publish a version inhouse. i don't know much maven, so what follows is probably the result of my ignorance of all things maven, but this is what i ran into:
* it tries to bring in some parent pom that has settings that i did not manage to override succesfully. it kept trying to connect to sodio.stratio.com. i ended up simpy deleting the parent pom reference.
* the profiles thing with scala 2.10 and 2.11 worked well when compiling and doing tests, but the resulting pom published to our in-house repository didnt work when it was used as a dependency in other projects. it seems scala.version and scala.binary.version had disappeared. i ended up putting scala.version and scala.binary.version in the main properties section and deleting the profiles.

**Comment by pmadrigal** [comment]
We are going to test it

**Comment by ccaballe** [comment]
This feature was solved in PR #34 
Please, open another issue for the second comment.
Thanks
