### ISSUE TITLE
Is it possible to connect to a MongoDB instance configured for SSL?

### ISSUE THREAD

**Issue by shulmang** [Stratio/spark-mongodb#3]
It looks like Casbah does support SSL connections (see: https://mongodb.github.io/casbah/guide/connecting.html) .  However, I'm not seeing in the MongodbConfigBuilder implementation how to configure the client to use SSL.  Any assistance is greatly appreciated.

**Comment by JSantosP** [comment]
We don't currently support this feature, however we're checking it out and will be developed as soon as possible.

**Comment by pmadrigal** [comment]
Now it's possible to connect with SSL. You can use this, in the branch feature/ssl. You have a brief instructions for use it in readme file.

We merge to master in the next days.

Thank you for your feedback!
