### ISSUE TITLE
java.lang.NoSuchMethodError:findTightestCommonTyp

### ISSUE THREAD

**Issue by lijian-ruckus** [Stratio/spark-mongodb#48]
I got the following exceptions when I ran the code in the "First Steps" section. 
5/10/17 03:42:43 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.HiveTypeCoercion$.findTightestCommonType()Lscala/Function2;
	at com.stratio.datasource.mongodb.schema.MongodbSchema.com$stratio$datasource$mongodb$schema$MongodbSchema$$compatibleType(MongodbSchema.scala:85)
	at com.stratio.datasource.mongodb.schema.MongodbSchema$$anonfun$4.apply(MongodbSchema.scala:46)

**Comment by lijian-ruckus** [comment]
I could run " saveToMongodb()" code successfully from the spark shell, but failed with the rest 
here are the environment settings:
spark 1.5.1, scala 2.11.7 
spark shell was invoked with the following command
spark shell --jars ./spark-mongodb_2.11.jar,./mongo-java-driver-2.13.0.jar,./casbah-core_2.11-2.8.0.jar,./casbah-commons_2.11-2.8.0.jar,./casbah-query_2.11-2.8.0.jar

I have tried to include different versions of spark-catalyst_xxx.jar, none of them fixes the issue.

**Comment by pmadrigal** [comment]
I guess you are using the master branch or a previous version which does not support Spark 1.5. We have a PR for adapting to Spark 1.5, so will be available this week.

Thanks for your feedback!

**Comment by pmadrigal** [comment]
We support spark 1.5.1 and scala 2.11 in 0.10.0 version wich is already available in central repository:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spark-mongodb_2.11%22
