### ISSUE TITLE
please support read preference option of mongodb

### ISSUE THREAD

**Issue by wonnyz** [Stratio/spark-mongodb#5]
Spark-mongodb just works with spark-sql shell with minimum efforts while it seems that mongodb hadoop connector is not spark-sql friendly. Very impressed with your hard work.

meanwhile, I could not find any connection option on read preference. Can we have one?
or it would be awesome if I can specify connection options using MongoClientURI Format.

**Comment by pmadrigal** [comment]
We are going to implement this in the next weeks.

Thank you for your feedback!

**Comment by pmadrigal** [comment]
This functionality is already supported in our last release ( version 0.8.6). It is available in Central Maven as well.

Thank you!
