### ISSUE TITLE
Support for splitKeyMin and splitKeyMax

### ISSUE THREAD

**Issue by kanielc** [Stratio/Spark-MongoDB#53]
Right now when a dataframe is created, the splits are generated using min/max.  The splitVector command allows you to customize min/max so that you get a more narrow number of splits.
This in turn would lead to a lot few partitions to create/read (which are often empty now with time series data).

**Comment by pmadrigal** [comment]
We are going to check it.

Thank you for your feedback!

**Comment by pmadrigal** [comment]
Hi @kanielc,

Could you give us more information?

How is your shard-key-pattern? How is the shard config (e.g. initial configuration of chunks number, default config)?

**Comment by kanielc** [comment]
I think now we're sharded, but I don't have visibility on those config
items.

Here's mongo-hadoop's use of the splits:
https://github.com/mongodb/mongo-hadoop/blob/master/core/src/main/java/com/mongodb/hadoop/splitter/StandaloneMongoSplitter.java

The data I'm using is mostly time series, so we have an index on
CreateDate, which I use to split.
By default, splitVector will give partitions across all the data (most
being empty), whereas with splitMin/splitMax, we get a lot fewer partitions.

**Comment by pmadrigal** [comment]
We already use splitvector in not sharded collections (Hadoop connector only split not sharded collection as well), but without min and max, so we will add it.

For sharded collections, we read the chunks borders, so you can execute a splitvector in MongoDB directly (Note that is an expensive operation).

If your collection is sharded, it's possible that was created with an initial number of chunks, so this could be another reason for empty chunks.

Thanks for your feedback!

**Comment by pmadrigal** [comment]
It's now supported in branch 0.11
