### ISSUE TITLE
not supported for mongoDB 3.0 and not supported fo spark 1.5

### ISSUE THREAD

**Issue by moonlightheng** [Stratio/spark-mongodb#62]
casbah.version is 2.8 and this version does not support mongoDB 3.0.
when I change the casbah version to 3.0 
it says "java.lang.NoClassDefFoundError: org/apache/spark/sql/types/UTF8String"
and I found that there is no class like UTF8String in spark sql 1.5
but MongodbReader use it at line 146
by DataFrameAPIExample

**Comment by pmadrigal** [comment]
Hi @moonlightheng ,

Casbah driver is compatible with mongoDB 3.0, you can find it [here](https://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/). Anyway, we will update casbah to 3.0 before long.

We don't know wich version of spark-mongodb are you using. We delete UTF8String in lastest versions and for Spark 1.5 you should use our 0.10.1 version.

We are going to update the example project dependency wich is not correct.

Please, let us know if this fix your problem or give us more information.

Thank you for your feedback!

**Comment by moonlightheng** [comment]
I didn't find version 0.10.x that day , I used 0.9.0 before
now I change to 0.10.x and it works 

thanks for your help and your project help me a lot  :)
