### ISSUE TITLE
Provide some simple Java examples

### ISSUE THREAD

**Issue by linjer** [Stratio/Spark-MongoDB#78]
I assume because you support scala, interfacing with your library via Java should be possible. Would be nice to get some examples off the bat to make this more obvious.

**Comment by pmadrigal** [comment]
Hi @linjer ,

Yes, we are fully compatible with Java so any example of a DataSource in Java would work using our config params.

I will update a simple Java example to the doc.

**Comment by linjer** [comment]
Thanks @pmadrigal ! I assumed Java should be workable, but the configuration with various types is not immediately obvious in Java and really felt like an early hurdle that could be solved with a simple example. Let me know if I can help.

**Comment by pmadrigal** [comment]
@linjer here is an example #86 , would be added to documentation very soon.

Hope it helps!
