### ISSUE TITLE
How to update data in collection with query, data, upsert, multi to update?

### ISSUE THREAD

**Issue by giaosudau** [Stratio/Spark-MongoDB#83]
Hi, 
I read the code and still don't find the way to update the collection like what I want.
I saw we have updatedFields option but it's only query path.
I want to know about the update_data path -> in $set update only field I want to update other keep it.
In Mongo update command have something I mostly use.
query -> find match records to update
update_data -> what field need to be update in $set: {field: value}
upsert 
multi.

Please help provide some example about that.
Thanks.

**Comment by pmadrigal** [comment]
Hi @giaosudau ,

We doesn't support multiUpdate, we allow replaceOne wich is enable with updateFields option, if you use it, you have to set the fields that you can check its values (filter) to replace this concrete element, and the dataframe have to have all the fields that you want to keep in the collection.

This project is not intended to do update operations.

Anyway, you can contribute and share an implementation for this.

Thanks for your feedback!

**Comment by giaosudau** [comment]
#95 
Please check this

**Comment by DeeeFOX** [comment]
watching for a graceful update operation too
