### ISSUE TITLE
Job stuck with the message.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [Stratio/Spark-MongoDB#88]
[2016-01-17 17:22:45,069] INFO  .apache.spark.SparkContext [] [akka://JobServer/user/context-supervisor/mongo] - Starting job: aggregate at MongodbSchema.scala:46

Hi,

I am seeing this whenever i run a job. Whatever the size of the collection may be. I am using Ec2 mongo which i am able to login and view data using Robomongo.

I am using java and using the approach provided in the example for java.

DataFrame df = sqlContext.read().format("com.stratio.datasource.mongodb").options(options).load();

options is provided correctly 

Map options = new HashMap();
        options.put("host", "10.1.1.0:27017");
        options.put("database", "xdb");
        options.put("collection", "mcollection");
        options.put("credentials", "user,db,password");

Can anyone point me to the right direction.

**Comment by pmadrigal** [comment]
Hi  @jamalahmedmaaz ,

Could you give us more info (versions used, mongodb config, error trace, etc ..)? 

This code apparently is correct.
