### ISSUE TITLE
Use the same ObjectId as '_id' of two different collections. What is the purpose of the "idasobjectid" parameter?

### ISSUE THREAD

**Issue by cperezmig** [Stratio/Spark-MongoDB#93]
Hi,

I would like to use the same ObjectId as '_id' of two different
collections. Is it possible? I have tried using the idasobjectid parameter
but it does not work. What is the purpose of this parameter?

Let see my example. I have two different collections in my Mongodb:
```
> db.createCollection("prueba1")
{ "ok" : 1 }
> db.createCollection("prueba2")
{ "ok" : 1 }
```

Let us suppose that we have the following dataframe (I am using pyspark):
```
sentenceData = sqlContext.createDataFrame([
    (0, "Hi I heard about Spark"),
    (0, "I wish Java could use case classes"),
    (1, "Logistic regression models are neat")
    ], ["label", "sentence"])
```

If I store it at the "prueba1" collection:
`sentenceData.write.format("com.stratio.datasource.mongodb").mode('append').options(host="localhost:27017", database="db1", collection="prueba1", idField='_id', splitKey='_id', splitSize='10', idasobjectid="true").save()`

In MongoDB the data is stored correctly:
```
> db.prueba1.findOne();
{
	"_id" : ObjectId("56b32f8a41b6b0acfcd070ea"),
	"label" : NumberLong(0),
	"sentence" : "Hi I heard about Spark"
}
> db.prueba1.count();
3
```

Now I read it to another dataframe:
```
sentences = sqlContext.read.format("com.stratio.datasource.mongodb").options(host="localhost:27017", database="db1", collection="prueba1", idField='_id', splitKey='_id', splitSize='10', idasobjectid="true").load()
sentences.count()
3
sentences.first()
Row(label=0, _id=u'56b32f8a41b6b0acfcd070ea', sentence=u'Hi I heard about Spark')
```

And now I store it at the prueba2 collection:
`sentenceData.write.format("com.stratio.datasource.mongodb").mode('append').options(host="localhost:27017", database="db1", collection="prueba2", idField='_id', splitKey='_id', splitSize='10', idasobjectid="true").save()`

The results in the Mongodb are:
```
> db.prueba2.findOne();
{
	"_id" : "56b32f8a41b6b0acfcd070ea",
	"label" : NumberLong(0),
	"sentence" : "Hi I heard about Spark"
}
> db.prueba2.count();
3
```

The "_id" is the same but in string format. What can I do to store it as an ObjectId?

**Comment by pmadrigal** [comment]
Hi @cperezmig ,

The idasobjectid parameter is currently implemented for reading operations. We will add support to write '_id' as objectId very soon.

You don't need to create collections previously in mongoDB (like in your first step), they will be created automatically.

Thanks for your feedback!

**Comment by cperezmig** [comment]
Hi @pmadrigal,

Thanks for your swift answer. If idasobjectid works only for reading operations, why when reading a collection the _id is a string in the dataframe?

I am glad to hear that create collections is now automaitc, at least with the last version I have tried, spark-mongodb crashed if the collection did not exist.

**Comment by pmadrigal** [comment]
Sorry @cperezmig , I didn't explain 'idAsObjectId' correctly.

This parameter allows filter '_id' field in MongoDB. This means, if the '_id' filter can be executed into MongoDB and the parameter is 'true', the value that you specify in the filter is converted to ObjectId, and will be filtered in the database.

Dataframe, is a representation of a relational table, wich you can query with a SQL like language, so by default, dataframe supports  Spark SQL dataTypes. Even so, it is possible create custom types: 
http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.sql.types.UserDefinedType

This is not in the backlog by the moment, but feel free to contribute!

**Comment by cperezmig** [comment]
Thank you for the explanation, Pedro.
Best regards
