### ISSUE TITLE
Possibility to run geo queries and/or setting a query built externally

### ISSUE THREAD

**Issue by danfran** [Stratio/Spark-MongoDB#99]
I am in the situation that I have to run million different geoqueries (`$near:{$geometry:{type:'Geometry', coordinates[lon,lat]}, $maxDistance:...}` etc) changing the coordinates for each of the query.

I am not using DataFrames but RDDs directly with `com.stratio.datasource.mongodb.rdd.MongodbRDD`.

I assume that in order to run geoqueries both for DataFrame and RDD is necessary to change the method `queryPartition` in the class `com.stratio.datasource.mongodb.reader.MongodbReader` right?

**Comment by pfcoperez** [comment]
@danfran I've just opened a PR including both versions of `$near`: https://github.com/Stratio/Spark-MongoDB/pull/100

You can pull it and check whether is enough for your requirements.

Btw, I might commit a change to include a customized filter type: mongo style within a string.

**Comment by danfran** [comment]
I saw it thank you. As I replied in #100, to complete, you should include `nearSphere`.

**Comment by pfcoperez** [comment]
@danfran They have been both added as well as a way of providing a `DBObject` as a filter description.
